print("Enter Value for robots eye")
eye = input()
print("Enter value for beeps mouth")
mouth = input()
print("\t\t\t##########")
print(f"\t\t\t#  {eye}   {eye} #")
print(f"\t\t\t#    {mouth}   #")
print("\t\t\t##########")
print("   000000000000000000000000000   ")
print("   000000000000000000000000000   ")
print("\t\t\t##########")
print("\t\t\t#  I AM  #")
print("\t\t\t#  BEEP  #")
print("\t\t\t##########")
print("\t\t\t##########")
print("\t\t\t###    ###")
print("\t\t\t###    ###")
print("\t\t\t###    ###")
print("\t\t\t###    ###")
print("\t\t\t###    ###")
print("\t\t\t###    ###")